name: TimeZone
description: Bindings for TimeZone.
language: objc
output: "foundation_bindings.dart"
objc-interfaces:
  include:
    - "NSTimeZone"
    - "NSDate"
headers:
  entry-points:
    - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSTimeZone.h"
preamble: |
  // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, return_of_invalid_type, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api

# functions:
#   exclude:
#     - ".*"
# structs:
#   exclude:
#     - ".*"
# unions:
#   exclude:
#     - ".*"
# globals:
#   exclude:
#     - ".*"
# macros:
#   exclude:
#     - ".*"
# enums:
#   exclude:
#     - ".*"
# unnamed-enums:
#   exclude:
#     - ".*"
