name: dartapp
description: A sample command-line application.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  ffigen:
    path: /Users/mit/dev/ffigen
