name: dartapp
description: A sample command-line application.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  ffigen:
    git: https://github.com/dart-lang/ffigen.git
