name: dart_json_serializable
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  http:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner:
  json_serializable:
  lints: ^3.0.0
