name: extention_type
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.0-0

# Add regular dependencies here.
#dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
