name: js_interop
description: A Flutter demo app for JS interop.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^0.5.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
