name: js_static_interop
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  js:

dev_dependencies:
  build_daemon: ">=2.0.0 <4.0.0"
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
